### ISSUE TITLE
"Cannot perform I/O on behalf of a different request" error when using signal on a fetch call in middleware

### ISSUE THREAD

**Issue by art-alexeyenko** [vercel/edge-runtime#169]
**Steps to reproduce / minimal reproducible example:**
1) Fork / use https://github.com/art-alexeyenko/lock-stock-mock as minimal repro example;
2) Deploy mock-express to Vercel - this will be used as an endpoint for fetch;
3) Deploy next-mid-ts to Vercel, set FETCH_ENDPOINT env variable to to https://{mock-express-vercel-url}/api;
Optional: set DEBUG env variable to "mock:*"
4) Check Function logs for next-mid-ts in Vercel;
5) Open two incognito windows with next-mid-ts homepage, refresh spam both for 10-12 seconds.

**Result:**
The following error occurs in logs either at step 4 or 5:

> Error: Cannot perform I/O on behalf of a different request. I/O objects (such as streams, request/response bodies, and others) created in the context of one request handler cannot be accessed from a different request's handler. This is a limitation of Cloudflare Workers which allows us to improve overall performance.
>     at lib/middleware/plugins/always-repro.ts:34:6
>     at <anonymous>
>     at lib/middleware/plugins/always-repro.ts:21:11
>     at lib/middleware/plugins/always-repro.ts:15:37
>     at lib/middleware/index.ts:12:46

Home page may fail to load with "Edge middleware failed" error screen.

**Expected:** 
Response is written into function logs each time, home page is loaded every time.

**Why is this important:**
Using signal is the preferred way to specify timeout for fetch requests from performance point of view and is a part of out of the box JS functionality.

**Some notes:**
Issue happens when executing logic from lib\middleware\plugins\always-repro.ts. It initializes an abort controller:
` private abortController = new AbortController();`
which is being used to set up timeout for fetch call:
```
 if (this.timeout) {
        abortTimeout = setTimeout(() => {
          this.abortController.abort();
        }, this.timeout);
      }
fetch(this.endpoint, {
        method: "POST",
        signal: this.abortController.signal,
      })
```

if timeout is not set, however, the issue still occurs. Passing the signal value into fetch is enough:
`signal: this.abortController.signal,
`

The repro example contains two 'plugins' for showcase: always-repro (issue is reproduced always when active) and maybe-repro (issue doesn't appear to occur when active). Their logic is virtually the same, with one small difference: AbortController in always-repro is defined as a class field, while in maybe-repro it is defined in request method scope. If the issue actually doesn't occur with maybe-repro, then perhaps the root cause is in the way the memory is managed and fields are being read.

To switch between them and see the behavior of the other plugin:
1) Modify next-mid-ts app;
2) In lib\middleware\index.ts comment lines 4 and 12, uncomment lines 3 and 13;
3) Redeploy next-mid-ts;
4) Use the same repro steps (check Function logs/spam home page over short period of time).

**Comment by Kikobeats** [comment]
Hello, thanks for reporting this.

It isn't actually an Edge Runtime issue, but an Edge Functions at Vercel issue.

We're working into land a solution. Let me keep you informed 🙂

**Comment by ambrauer** [comment]
Hi @Kikobeats - just curious if there's any update on this issue?

**Comment by Kikobeats** [comment]
We believe this has been resolved since some time ago – I'm going to close for now, but please feel free to comment if you experience any issue related 🙂
