### ISSUE TITLE
Importing Functions from local files with dynamic paths

### ISSUE THREAD

**Issue by nairol203** [vercel/edge-runtime#295]
## Bug Report
I am trying to dynamically import a function with the filename given in a function argument.
This are my approaches and outcomes:

**First approach: require()**

Line of Code:
```const file = await require(`./${fileName}`);```
And the compiler options:
```
"module": "ESNext",
"target": "CommonJS",
"esModuleInterop": true,
```` 

This is giving me this error:
```
ReferenceError: require is not defined
    at (api/test.js:116:87)
    at (api/test.js:116:24)
    at (api/test.js:130:28)
```

However, when i trying the same with an static path and not the variable in the path, it works, no errors.
```const file = await require('./test');```

**Second approach: import()**

Line of Code:
```const file = await import(`./${fileName}`);```
```const file = await import('./test');```
And my typescript compiler options:
```
"module": "es2020",
"target": "es2020",
"esModuleInterop": true,
```` 

But that is giving me this error, with the variable in the path and also without.
```
Error: internal error
    at (api/test.js:87:52)
    at (api/test.js:101:34)
    at (api/test.js:23:11)
```

**Comment by Kikobeats** [comment]
Sorry, that is not supported and not expected to be supported.

You should to get your code ready before passing it to Edge Runtime, like this example:
https://edge-runtime.vercel.app/packages/runtime#usage

🙂
