### ISSUE TITLE
@edge-runtime/jest-environment fails when you include 'next/navigation'

### ISSUE THREAD

**Issue by adamjmcgrath** [vercel/edge-runtime#406]
## Bug Report

**Current behavior**

When you import `next/navigation` (and possibly others) in a test that uses `@edge-runtime/jest-environment` - you get a react import error:

```js
/**
 * @jest-environment @edge-runtime/jest-environment
 */
import { redirect }  from 'next/navigation';

describe('tmp', () => {
  test('should create a state', async () => {
    expect(redirect).toBeDefined();
  });
});
```

Fails with:

```bash
  ● Test suite failed to run

    This entry point is not yet supported outside of experimental channels

      at node_modules/react/cjs/react.shared-subset.development.js:18:7
      at Object.<anonymous> (node_modules/react/cjs/react.shared-subset.development.js:19:5)
      at Object.<anonymous> (node_modules/react/react.shared-subset.js:6:20)
```

**Expected behavior/code**

Test should pass with 'next/navigation' included.

**Additional context/screenshots**

It works in `2.1.0`, fails in `2.2.0`

![image](https://github.com/vercel/edge-runtime/assets/1299658/8ec91789-670d-4a3c-9a97-a4fd073c4fa4)

https://replit.com/@AdamMcGrath/LustrousCheeryDictionary (run `jest` from shell)

**Comment by Kikobeats** [comment]
@adamjmcgrath thanks for reporting. A big refactor was shipped between 2.1.0 and 2.2.0. I'm trying to understand the jest error 🤔

**Comment by Kikobeats** [comment]
Can you confirm https://github.com/vercel/edge-runtime/releases/tag/%40edge-runtime%2Fjest-expect%401.1.2 fixed the issue? 🙂

**Comment by adamjmcgrath** [comment]
https://github.com/vercel/edge-runtime/releases/tag/%40edge-runtime%2Fjest-environment%402.2.4 works for me 👍 thanks @Kikobeats
